<script setup>
/*
 VO Dub's own roles editor -- NOT a port of RolesEditorApp.vue's shape
 any more (see nodes/vo_dub_library.py's read_dub_roles_document): a
 real _dub_roles.json is a full CASTING DOCUMENT generated by a
 project's own script (this repo's example: Observation's
 scripts/06_assign_roles.py), keyed by role CODE (a dict, not a list),
 each entry carrying character/gender/actor/description/dub_direction/
 notes plus computed stats (lines/audio_minutes/...) -- role identity
 there comes from matching regex rules against audio_key, not from
 vo_dataset.csv's own noisy `speaker` column. This addon did not
 generate any of that and doesn't try to reproduce the matching -- see
 this file's own docstring in vo_dub_library.py for why row<->role
 matching stays manual (the line editor's own bulk "Assign voice...").

 The ONE thing this addon adds is `speaker` (a real CosyVoice preset)
 per role, and it's the ONLY field edited here -- everything else is
 read-only display, both because it isn't this addon's to invent and
 because _dub_roles.json is typically GENERATED (fully rewritten by
 that script on every run, same class of file as vo_dataset.csv) --
 re-running it would blow away anything else this editor changed. The
 user has explicitly chosen to accept the one exception: writing
 `speaker` directly into this same file, knowing a future regeneration
 wipes it (that script's own per-role dict literals don't carry the
 field at all).
*/
import { ref, computed, watch, onMounted, onBeforeUnmount } from "vue";
import Dialog from "primevue/dialog";
import Message from "primevue/message";
import InputText from "primevue/inputtext";
import Button from "primevue/button";
import SpeakerPickerDialog from "../line_editor/SpeakerPickerDialog.vue";
import { usePanelWidth } from "../shared/panel_width.js";
import { useFontSize } from "../shared/font_size.js";
import DialogHeader from "../shared/DialogHeader.vue";
import {
    markDubRoleStale, joinPath,
    SCRIPT_EDITOR_API as FILE_API, SPEAKER_PRESETS_API as PRESETS_API, VO_DUB_API,
} from "../../web/fl_common.js";

const props = defineProps({
    root: { type: String, required: true },
    onClose: { type: Function, required: true },
});

const SAVE_DEBOUNCE_MS = 600;
const POLL_MS = 3000;
const EDIT_QUIET_MS = 1500;

const fullPath = joinPath(props.root, "_dub_roles.json");
const visible = ref(true);
/*
 The FULL parsed document (project/generated_by/totals/roles/
 unmatched_keys/...) -- saved back as a whole, so nothing this addon
 didn't generate ever gets dropped. {roles: {}} until the first load
 resolves.
*/
const doc = ref({ roles: {} });
const presets = ref([]);
const speakerSampleDir = ref(""); // folder holding each preset's own .pt (and a same-named sample .mp3/.wav) -- see loadPresets
const status = ref("");
const seeding = ref(false);
const { cssWidth: panelWidthCss, setWidth: setPanelWidth, presets: widthPresets } = usePanelWidth({
    storageKey: "FL_CosyVoice3.DubRolesEditor.widthPx",
    defaultWidth: 1200,
    presets: [900, 1200],
});
const { fontSizePx: cardFontSizePx, decrease: decreaseCardFontSize, increase: increaseCardFontSize } = useFontSize({
    storageKey: "FL_CosyVoice3.DubRolesEditor.fontSizePx",
    defaultSize: 13,
});

let lastSavedText = null;
let lastLocalEditAt = 0;
let saveTimer = null;
let pollTimer = null;
/*
 Last speaker value we already ran a stale-scan for, per role code --
 seeded from disk on every load so a genuine change (typed or picked) is
 detected relative to what's ACTUALLY saved, not just "different from a
 moment ago".
*/
const lastNotifiedSpeaker = new Map();

function setStatus(text) {
    status.value = text;
}

/*
 [code, entry] pairs, biggest role first -- the same "lines descending"
 order 06_assign_roles.py's own console summary prints in, so a role
 list here reads the same way its generator's own output does.
*/
const roleEntries = computed(() => {
    const roles = doc.value?.roles || {};
    return Object.entries(roles).sort((a, b) => (b[1]?.lines || 0) - (a[1]?.lines || 0));
});

function displayName(entry, code) {
    return entry.character || code;
}
function notesList(entry) {
    return Array.isArray(entry.notes) ? entry.notes : [];
}
function exampleFiles(entry) {
    return Array.isArray(entry.longest_files) ? entry.longest_files : [];
}

function serialize() {
    return JSON.stringify(doc.value, null, 2);
}

async function flushSave() {
    const text = serialize();
    if (text === lastSavedText) return;
    try {
        const resp = await fetch(`${FILE_API}/write`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ path: fullPath, content: text }),
        });
        const data = await resp.json();
        if (data.error) {
            setStatus(`Save error: ${data.error}`);
            return;
        }
        lastSavedText = text;
        setStatus(`Saved ${new Date().toLocaleTimeString()}`);
    } catch (e) {
        setStatus(`Save failed: ${e}`);
    }
}

function scheduleSave() {
    lastLocalEditAt = Date.now();
    if (saveTimer) clearTimeout(saveTimer);
    saveTimer = setTimeout(flushSave, SAVE_DEBOUNCE_MS);
}

/*
 Recasting a role changes what every VO row TAGGED with that code (and
 not carrying its own manual override -- see
 nodes/vo_dub_library.py's resolved_speaker) resolves to. See
 fl_common.js's markDubRoleStale for what actually gets un-readied
 server-side (_dub_state.json entries, not script files). Only called on
 a discrete "this value is now committed" moment, never on every
 keystroke.
*/
function notifyIfSpeakerChanged(code, entry) {
    const prev = lastNotifiedSpeaker.get(code);
    if (prev === entry.speaker) return;
    lastNotifiedSpeaker.set(code, entry.speaker);
    markDubRoleStale(props.root, code).then((result) => setStatus(result.message));
}

function onSpeakerCommitted(code, entry) {
    scheduleSave();
    notifyIfSpeakerChanged(code, entry);
}

async function loadPresets() {
    try {
        const resp = await fetch(PRESETS_API);
        const data = await resp.json();
        presets.value = data.presets || [];
        speakerSampleDir.value = data.dir || "";
    } catch (e) {
        presets.value = [];
        speakerSampleDir.value = "";
    }
}

/*
 ── speaker picker dialog -- same "stateless dialog, this editor tracks
 which role it's for" contract as LineEditorApp.vue's own
 openSpeakerPicker/onSpeakerPicked, reusing the identical component
 (with sample-audition playback) instead of the plain filterable
 Dropdown this file used to have.
*/
const speakerPickerVisible = ref(false);
const speakerPickerTarget = ref(null); // [code, entry]
function openSpeakerPicker(code, entry) {
    speakerPickerTarget.value = [code, entry];
    speakerPickerVisible.value = true;
}
function onSpeakerPicked(preset) {
    const target = speakerPickerTarget.value;
    if (!target) return;
    const [code, entry] = target;
    entry.speaker = preset;
    onSpeakerCommitted(code, entry);
}

async function loadFromDisk({ isPoll = false } = {}) {
    try {
        const resp = await fetch(`${FILE_API}/read?path=${encodeURIComponent(fullPath)}`);
        const data = await resp.json();
        if (data.error) {
            setStatus(`Read error: ${data.error}`);
            return;
        }
        if (!data.exists) {
            if (!isPoll) {
                doc.value = { roles: {} };
                lastSavedText = "";
                setStatus("_dub_roles.json does not exist yet -- click \"Seed from dataset\" below");
            }
            return;
        }
        if (isPoll && Date.now() - lastLocalEditAt < EDIT_QUIET_MS) return;
        if (data.content === lastSavedText) return;
        let parsed;
        try {
            parsed = JSON.parse(data.content);
        } catch (e) {
            setStatus(`_dub_roles.json is not valid JSON: ${e}`);
            return;
        }
        const roles = (parsed && typeof parsed.roles === "object" && parsed.roles) || {};
        /*
         Backfill an empty `speaker` on every role so the Dropdown below
         always binds to a real string, never `undefined` -- harmless on
         save (adds "speaker": "" to a role that never had one, exactly
         like nodes/vo_dub_library.py's seed_dub_roles already does for
         a freshly-added role).
        */
        for (const entry of Object.values(roles)) {
            if (entry && typeof entry === "object" && entry.speaker === undefined) entry.speaker = "";
        }
        doc.value = { ...parsed, roles };
        for (const [code, entry] of Object.entries(roles)) {
            lastNotifiedSpeaker.set(code, entry.speaker);
        }
        lastSavedText = serialize();
        if (!isPoll) setStatus(`Loaded ${roleEntries.value.length} role(s)`);
    } catch (e) {
        setStatus(`Read failed: ${e}`);
    }
}

/*
 Populates _dub_roles.json from vo_dataset.csv's own distinct `speaker`
 tags (see nodes/vo_dub_library.py's seed_dub_roles) -- additive only,
 never touches an existing role (a curated one from a project's own
 casting script included), so running this again after assigning some
 voices never resets them. Of limited use once a project already has a
 real casting document like this one -- its role codes are curated
 identities, not raw csv tags, so seeding only fills in codes nothing
 there already covers.
*/
async function seedFromDataset() {
    seeding.value = true;
    try {
        const resp = await fetch(`${VO_DUB_API}/seed_roles`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ root: props.root }),
        });
        const data = await resp.json();
        if (data.error) {
            setStatus(`Seed error: ${data.error}`);
            return;
        }
        /*
         Reload FIRST -- loadFromDisk sets its own "Loaded N role(s)"
         status when it isn't a poll, which would otherwise immediately
         overwrite the more informative "Added N role(s)" message below.
        */
        await loadFromDisk();
        setStatus(data.added.length ? `Added ${data.added.length} role(s): ${data.added.join(", ")}` : "Nothing new to add");
    } catch (e) {
        setStatus(`Seed failed: ${e}`);
    } finally {
        seeding.value = false;
    }
}

function close() {
    if (saveTimer) {
        clearTimeout(saveTimer);
        flushSave();
    }
    for (const [code, entry] of roleEntries.value) notifyIfSpeakerChanged(code, entry);
    if (pollTimer) clearInterval(pollTimer);
    props.onClose();
}

watch(visible, (v) => { if (!v) close(); });

onMounted(async () => {
    loadPresets();
    await loadFromDisk();
    pollTimer = setInterval(() => loadFromDisk({ isPoll: true }), POLL_MS);
});

onBeforeUnmount(() => {
    if (pollTimer) clearInterval(pollTimer);
});
</script>

<template>
    <Dialog
        v-model:visible="visible"
        :modal="false"
        :draggable="false"
        close-on-escape
        header=" "
        :style="{ width: panelWidthCss }"
        class="roles-dialog"
    >
        <template #header>
            <DialogHeader
                title="VO Dub Roles" :status="status"
                :width-presets="widthPresets" :set-width="setPanelWidth"
                :font-size-decrease="decreaseCardFontSize" :font-size-increase="increaseCardFontSize"
            >
                <template #after>
                    <Button
                        label="Seed from dataset" size="small" text
                        :icon="seeding ? 'pi pi-spin pi-spinner' : 'pi pi-database'"
                        :disabled="seeding"
                        title="Add every distinct speaker tag from vo_dataset.csv that isn't a role here yet"
                        @click="seedFromDataset"
                    />
                </template>
            </DialogHeader>
        </template>

        <Message v-if="!roleEntries.length" severity="info" :closable="false">
            No roles yet -- click "Seed from dataset" above to create one per distinct speaker tag.
        </Message>

        <div class="roles-list" :style="{ fontSize: `${cardFontSizePx}px` }">
            <div v-for="[code, entry] in roleEntries" :key="code" class="role-card">
                <div class="role-head">
                    <span class="role-name">{{ displayName(entry, code) }}</span>
                    <span class="role-code" title="Role code -- read-only here, this addon doesn't own this file's identity model">{{ code }}</span>
                    <span v-if="entry.gender" class="role-gender" :title="entry.gender_evidence || ''">{{ entry.gender }}</span>
                    <span v-if="entry.actor" class="role-actor">{{ entry.actor }}</span>
                </div>

                <p v-if="entry.description" class="role-description">{{ entry.description }}</p>
                <p v-if="entry.dub_direction" class="role-dub-direction">{{ entry.dub_direction }}</p>
                <ul v-if="notesList(entry).length" class="role-notes">
                    <li v-for="(note, i) in notesList(entry)" :key="i">{{ note }}</li>
                </ul>

                <div class="role-stats">
                    <span v-if="entry.lines !== undefined">{{ entry.lines }} line(s)</span>
                    <span v-if="entry.audio_minutes !== undefined">{{ entry.audio_minutes }} min</span>
                    <span v-if="entry.lines_needing_translation">{{ entry.lines_needing_translation }} need translation</span>
                    <span v-if="entry.lines_without_any_text">{{ entry.lines_without_any_text }} no text</span>
                </div>
                <div v-if="exampleFiles(entry).length" class="role-examples" title="Longest lines for this role -- a quick sample to listen to">
                    e.g. {{ exampleFiles(entry).join(", ") }}
                </div>

                <div class="role-speaker-row">
                    <InputText
                        v-model="entry.speaker"
                        placeholder="Speaker preset"
                        title="Real CosyVoice preset this role resolves to"
                        class="role-speaker"
                        @update:model-value="scheduleSave()"
                        @blur="notifyIfSpeakerChanged(code, entry)"
                    />
                    <Button
                        icon="pi pi-microphone"
                        size="small"
                        title="Pick a speaker from the preset gallery"
                        @click="openSpeakerPicker(code, entry)"
                    />
                </div>
            </div>
        </div>
    </Dialog>

    <SpeakerPickerDialog
        v-model:visible="speakerPickerVisible"
        :presets="presets"
        :sample-dir="speakerSampleDir"
        @select="onSpeakerPicked"
    />
</template>

<style scoped src="../style/DubRolesEditorApp.css"></style>
